{
  pkgs,
  jbot-agent-py,
  jbot-prompt-txt,
  ...
}:
let
  mockGemini = pkgs.writeShellScriptBin "gemini" ''
    # Parse arguments
    while [[ $# -gt 0 ]]; do
      case $1 in
        -p)
          PROMPT="$2"
          shift 2
          ;;
        *)
          shift
          ;;
      esac
    done

    # Save the prompt content for inspection
    mkdir -p .jbot/prompts
    echo "$PROMPT" > ".jbot/prompts/prompt_$AGENT_NAME.txt"
    
    # Verify hierarchical visibility in prompt
    case "$AGENT_NAME" in
      sub_agent)
        # Should see parent CEO
        if ! grep -q "### Supervisors (Parent Projects)" ".jbot/prompts/prompt_sub_agent.txt"; then
          echo "Error: sub_agent did not see Supervisor section"
          exit 1
        fi
        if ! grep -q "parent_ceo" ".jbot/prompts/prompt_sub_agent.txt"; then
          echo "Error: sub_agent did not see parent_ceo"
          exit 1
        fi
        ;;
      parent_ceo)
        # Should see sub-project agent
        if ! grep -q "### Sub-projects (Nested Agents)" ".jbot/prompts/prompt_parent_ceo.txt"; then
          echo "Error: parent_ceo did not see Sub-projects section"
          exit 1
        fi
        if ! grep -q "sub_agent" ".jbot/prompts/prompt_parent_ceo.txt"; then
          echo "Error: parent_ceo did not see sub_agent"
          exit 1
        fi
        ;;
    esac

    echo '{"scope": "local", "status": "success", "summary": "Hierarchy test passed for '$AGENT_NAME'"}' > "$MEMORY_OUTPUT"
  '';
in
pkgs.runCommand "jbot-hierarchy-unit-test"
{
  nativeBuildInputs = [
    pkgs.python3
    pkgs.coreutils
    pkgs.findutils
    pkgs.jq
    mockGemini
  ];
} ''
  # Setup Root Project
  ROOT_DIR=$TMPDIR/root
  mkdir -p $ROOT_DIR/.jbot
  cd $ROOT_DIR
  echo "Goal: Root Vision" > .project_goal
  echo "# Task Board" > TASKS.md

  # Setup Sub Project
  SUB_DIR=$ROOT_DIR/sub-project
  mkdir -p $SUB_DIR/.jbot

  # Global agents.json (simulated)
  # In a real NixOS setup, this is generated by jbot.nix
  echo '{
    "parent_ceo": {"role": "CEO", "description": "Global CEO", "projectDir": "'$ROOT_DIR'"},
    "sub_agent": {"role": "Lead", "description": "Sub Agent", "projectDir": "'$SUB_DIR'", "supervisor": "parent_ceo"}
  }' > $ROOT_DIR/.jbot/agents.json
  
  # Copy agents.json to sub project as well (jbot.nix does this filtering)
  cp $ROOT_DIR/.jbot/agents.json $SUB_DIR/.jbot/agents.json

  export PROMPT_FILE="${jbot-prompt-txt}"
  export GEMINI_PACKAGE="gemini"

  # 1. Run parent_ceo
  cd $ROOT_DIR
  export PROJECT_DIR=$ROOT_DIR
  export AGENT_NAME="parent_ceo"
  export AGENT_ROLE="CEO"
  export AGENT_DESCRIPTION="Global CEO"
  export MEMORY_OUTPUT=".jbot/queues/parent_ceo.json"
  python3 ${jbot-agent-py}

  # 2. Run sub_agent
  cd $SUB_DIR
  export PROJECT_DIR=$SUB_DIR
  export AGENT_NAME="sub_agent"
  export AGENT_ROLE="Lead"
  export AGENT_DESCRIPTION="Sub Agent"
  export MEMORY_OUTPUT=".jbot/queues/sub_agent.json"
  python3 ${jbot-agent-py}

  echo "Hierarchy visibility test passed!"
  touch $out
''
